name: BERTopic-Tutorial
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - pandas=2.3.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - jupyter
  - ipykernel
  - ipython
  - pip:
    # 核心主题建模包
    - bertopic==0.15.0
    - sentence-transformers==2.2.2
    - transformers==4.29.1
    - tokenizers==0.13.3
    - sentencepiece==0.2.0
    
    # 聚类和降维
    - hdbscan==0.8.39
    - umap-learn==0.5.3
    - pynndescent==0.5.13
    
    # 中文分词
    - jieba==0.42.1
    - nltk==3.9.1
    - regex==2024.11.6
    
    # 数据处理和可视化
    - plotly==6.2.0
    - wordcloud==1.9.4
    - openpyxl==3.1.5
    - tqdm==4.67.1
    
    # 深度学习框架
    - torch==2.2.2
    - torchvision==0.17.2
    - torchaudio==2.2.2
    
    # 其他工具
    - huggingface-hub==0.14.1
    - fsspec==2025.5.1
    - click==8.2.1
    - narwhals==1.44.0
    - hf-xet==1.1.5
    - numba==0.61.2
    - llvmlite==0.44.0
    
    # 文本处理
    - nltk>=3.8.1
    - wordcloud>=1.9.0
    
    # 数据可视化
    - bokeh>=3.2.0
    
    # 评估指标
    - scikit-learn-extra>=0.2.0
    
    # 其他工具
    - joblib>=1.3.0
    - psutil>=5.9.0
    - memory-profiler>=0.61.0
    
    # 可选：用于更好的中文支持
    - pypinyin>=0.49.0
    - zhon>=1.1.5
    
    # 可选：用于更高级的可视化
    - pyLDAvis>=3.4.0
    - gensim>=4.3.0
    
    # 可选：用于模型保存和加载
    - pickle5>=0.0.12
    
    # 可选：用于并行处理
    - multiprocess>=0.70.0
    
    # 可选：用于进度条美化
    - rich>=13.0.0
    
    # 可选：用于配置管理
    - pyyaml>=6.0
    
    # 可选：用于日志管理
    - loguru>=0.7.0 